name: mobile
description: "Dynamik Devs mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.0
  dio: ^5.0.0
  freezed_annotation: any
  json_annotation: any
  go_router: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: any
  freezed: any
  json_serializable: any

flutter:
  uses-material-design: true
